name: Python

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.7'

    - name: Install dependencies
      run: |
        sudo apt-get install graphviz
        python -m pip install --upgrade pip
        pip install flake8 tensorflow numpy keras sklearn pydot

    - name: Build
      working-directory: ./ML
      run: python -m py_compile ./main.py

    - name: Syntax checker
      working-directory: ./ML
      run: flake8 . --max-line-length 150
